import "./globals.css";
import { Montserrat } from "next/font/google";
import { ThemeProvider } from "./components/exports";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
    title: "Aden Teo's Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ThemeProvider>
            <html lang="en" className="scroll-smooth">
                <body className={montserrat.className}>{children}</body>
            </html>
        </ThemeProvider>
    );
}
